# Generated by Django 4.1.3 on 2023-03-18 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Text', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='submition',
            fields=[
                ('submition_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('suggestions', models.CharField(default='', max_length=1000, null=True)),
                ('accuracy', models.IntegerField()),
                ('answer_status', models.CharField(blank=True, max_length=20, null=True)),
                ('flag', models.BooleanField(default=True)),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Text.text')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submitions',
            },
        ),
    ]
