# Generated by Django 4.1.3 on 2023-03-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Submitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submition',
            old_name='email',
            new_name='id',
        ),
    ]
